plugins {
    id 'com.android.library'
    id 'maven-publish'
}

group = 'com.github.FlutterGenerator'

android {
    namespace 'animation.library'
    compileSdkVersion 36

    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 36
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    publishing {
        singleVariant("release") {
            withSourcesJar()
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                groupId = 'com.github.FlutterGenerator'
                artifactId = 'AnimationLGL'
                version = 'v0.0.1'

                from components.release
            }
        }
    }
}